---
apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: pvConf
spec:
  credentials:
    secretRef:
      key: instanceCredentials
      name: grafana-instance
      namespace: crossplane
    source: Secret
  oncallUrl: https://oncall-ops-eu-south-0.grafana.net/oncall/
  smUrl: https://synthetic-monitoring-api-eu-south-0.grafana-ops.net
  url: https://ops.grafana-ops.net
